import { isDevMode } from "@angular/core";
//export const BASE = `http://localhost:8080`;
//export const BASE = `https://api.utterfare.com`;
export const BASE = isDevMode() ? 'http://localhost:8080' : 'https://api.utterfare.com';
export const VENDOR_PROFILE_ROUTE = `${BASE}/vendor/profile`;
export const SEARCH_ROUTE = `${BASE}/search`;
export const MENU_ITEM_ROUTE = `${BASE}/vendor/items`;
export const MENU_ITEM_REVIEWS_ROUTE = `${MENU_ITEM_ROUTE}/reviews`;
export const MEDIA_ROUTE = `${BASE}/media`;
export const USER_ROUTE = `${BASE}/users`;
export const PROFILE_ROUTE = `${BASE}/profile`;
export const FEED_ROUTE = `${PROFILE_ROUTE}/feed`;
export const FOLLOWERS_ROUTE = `${PROFILE_ROUTE}/followers`;