name: Publish to production

# Controls when the workflow will run 
on: 
  push: 
    branches: [ master ]

  pull_request: 
    types: [merged]
    branches: [master]

  workflow_dispatch: 

jobs: 
  deploy: 
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v4

    - name: Sync files
      if: success()
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with: 
        server: gator4070.hostgator.com
        username: cmeehan
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/utterfare/browser/
        server-dir: utterfare.com/
        state-name: ./.sync-state.json